######################################################################################
#
# export_bigdigits.py
#
# Writes ../../RTK_Everywhere/fontBigDigits.h: the Terminus Bold big digit glyphs from
# bigtext_fonts.py (bigtext_fonts.FIRMWARE_VARIANT, the same glyphs the render_bigtext.py
# mockups used), as displayBitmap() bitmaps (column-major, bit 0 = top row, 8-row bands),
# at the heights the firmware's fit rule tries (bigtext_fonts.FIRMWARE_FIT,
# printBigDigits() in Display.ino).
#
# Use: python export_bigdigits.py
#
######################################################################################

from pathlib import Path

import bigtext_fonts

OUT_H = Path(__file__).parent.parent.parent / "RTK_Everywhere" / "fontBigDigits.h"
HEIGHTS = tuple(sorted({height for height, gap in bigtext_fonts.FIRMWARE_FIT}, reverse=True))
CHARS = "0123456789.>mN/A"


def c_name(ch):
    return {".": "dot", ">": "gt", "/": "slash"}.get(ch, ch)


def bitmap_bytes(glyph):
    height, width = glyph.shape
    bands = (height + 7) // 8
    data = []
    for band in range(bands):
        for col in range(width):
            byte = 0
            for bit in range(8):
                row = band * 8 + bit
                if row < height and glyph[row, col]:
                    byte |= 1 << bit
            data.append(byte)
    return data


def main():
    out = ["// Generated by Firmware/Tools/EPaper_Emulator/export_bigdigits.py - do not edit.",
           "// 184x88 e-paper big digits: Terminus Font Bold (SIL OFL 1.1, see",
           "// Tools/EPaper_Emulator/assets/fonts/Terminus-OFL.txt) - ter-u32b for 20 px digits,",
           "// ter-u28b for 18 px - cropped to each glyph's ink for proportional spacing. Every glyph",
           "// is the set's full height, drawn from the top of the digit ink box. See printBigDigits()",
           "// in Display.ino.",
           "",
           "#ifndef __FONT_BIG_DIGITS_H__",
           "#define __FONT_BIG_DIGITS_H__",
           "",
           "typedef struct",
           "{",
           "    char character;",
           "    uint8_t width;",
           "    const uint8_t *bitmap;",
           "} bigDigitGlyph_t;",
           "",
           "typedef struct",
           "{",
           "    uint8_t height;",
           "    uint8_t glyphCount;",
           "    const bigDigitGlyph_t *glyphs;",
           "} bigDigitFont_t;",
           ""]
    for height in HEIGHTS:
        glyphs = bigtext_fonts.firmware_glyphs(height)
        entries = []
        for ch in CHARS:
            g = glyphs[ch]
            name = f"bigDigit{height}_{c_name(ch)}"
            data = bitmap_bytes(g)
            out.append(f"const uint8_t {name}[] = {{")
            for i in range(0, len(data), 16):
                out.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
            out.append("};")
            entries.append(f"    {{'{ch}', {g.shape[1]}, {name}}},")
        out.append(f"const bigDigitGlyph_t bigDigit{height}Glyphs[] = {{")
        out += entries
        out.append("};")
        out.append(f"const bigDigitFont_t bigDigits{height} = {{{height}, {len(CHARS)}, bigDigit{height}Glyphs}};")
        out.append("")
    out.append("#endif // __FONT_BIG_DIGITS_H__")
    OUT_H.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"-> {OUT_H}")


if __name__ == "__main__":
    main()
