// AUTO-GENERATED by Firmware/Tools/generate_settings_defaults_js.py from settings.h.
// Do not hand-edit - rerun the script instead.
const SETTINGS_DEFAULTS = {
  "ARPLoggingInterval": {
    "default": 10,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "RINEXFileDuration": {
    "default": null,
    "platforms": [
      "FPM",
      "FacetX5"
    ]
  },
  "RINEXObsInterval": {
    "default": null,
    "platforms": [
      "FPM",
      "FacetX5"
    ]
  },
  "alignedLogFiles": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "antennaHeightM": {
    "default": 1.8,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "antennaPhaseCenter": {
    "default": null,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "autoFirmwareCheckMinutes": {
    "default": 1440,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "baseTypeFixed": {
    "default": false,
    "platforms": [
      "EVK",
      "FacetX5",
      "Torch",
      "Postcard",
      "TX2",
      "FPM",
      "FPL",
      "FPX"
    ]
  },
  "baseTypeSurveyIn": {
    "default": true,
    "platforms": [
      "EVK",
      "FacetX5",
      "Torch",
      "Postcard",
      "TX2",
      "FPM",
      "FPL",
      "FPX"
    ]
  },
  "bluetoothRadioType": {
    "default": 2,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "constellation_BeiDou": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "constellation_GLONASS": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "constellation_GPS": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "constellation_Galileo": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "constellation_NavIC": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2"
    ]
  },
  "constellation_QZSS": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "constellation_SBAS": {
    "default": true,
    "platforms": [
      "FPM",
      "FacetX5"
    ]
  },
  "coordinateInputType": {
    "default": 0,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "correctionsSourcesLifetime": {
    "default": 30,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "dataPortBaud": {
    "default": 230400,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "dataPortChannel": {
    "default": 0,
    "platforms": [
      "FacetX5"
    ]
  },
  "dynamicModel": {
    "default": null,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableARPLogging": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "enableAutoFirmwareUpdate": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableBeeper": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FPX",
      "TX2",
      "Torch"
    ]
  },
  "enableEspNow": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableExtCorrRadio": {
    "default": null,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "enableExternalHardwareEventLogging": {
    "default": false,
    "platforms": [
      "EVK",
      "FacetX5"
    ]
  },
  "enableExternalPulse": {
    "default": true,
    "platforms": [
      "EVK",
      "FacetX5"
    ]
  },
  "enableGnssToUsbSerial": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableLogging": {
    "default": true,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "enableLoggingRINEX": {
    "default": false,
    "platforms": [
      "FPM",
      "FacetX5"
    ]
  },
  "enableLora": {
    "default": false,
    "platforms": [
      "FPL",
      "FPM",
      "FPX",
      "Torch"
    ]
  },
  "enableMultipathMitigation": {
    "default": true,
    "platforms": [
      "Torch"
    ]
  },
  "enableNmeaOnRadio": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "enableNtripCaster": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableNtripClient": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableNtripServer": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableTcpClient": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableTcpServer": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "enableTiltCompensation": {
    "default": true,
    "platforms": [
      "FPL",
      "FPM",
      "FPX",
      "Torch"
    ]
  },
  "enableUdpServer": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "espnowPeerCount": {
    "default": 0,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "espnowPeer_0": {
    "default": "00:00:00:00:00:00",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "espnowPeer_1": {
    "default": "00:00:00:00:00:00",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "espnowPeer_2": {
    "default": "00:00:00:00:00:00",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "espnowPeer_3": {
    "default": "00:00:00:00:00:00",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "espnowPeer_4": {
    "default": "00:00:00:00:00:00",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ethernetDHCP": {
    "default": true,
    "platforms": [
      "EVK"
    ]
  },
  "ethernetDNS": {
    "default": null,
    "platforms": [
      "EVK"
    ]
  },
  "ethernetGateway": {
    "default": null,
    "platforms": [
      "EVK"
    ]
  },
  "ethernetIP": {
    "default": null,
    "platforms": [
      "EVK"
    ]
  },
  "ethernetNtpPort": {
    "default": 123,
    "platforms": [
      "EVK"
    ]
  },
  "ethernetSubnet": {
    "default": null,
    "platforms": [
      "EVK"
    ]
  },
  "externalEventPolarity": {
    "default": false,
    "platforms": [
      "FacetX5"
    ]
  },
  "externalPulseLength": {
    "default": 200000,
    "platforms": [
      "EVK",
      "FacetX5"
    ]
  },
  "externalPulsePolarity": {
    "default": 1,
    "platforms": [
      "EVK",
      "FacetX5"
    ]
  },
  "externalPulseTimeBetweenPulse": {
    "default": 1000000,
    "platforms": [
      "EVK",
      "FacetX5"
    ]
  },
  "fixedAltitude": {
    "default": 1560.089,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "fixedBaseCoordinateTypeECEF": {
    "default": true,
    "platforms": [
      "EVK",
      "FacetX5",
      "Torch",
      "Postcard",
      "TX2",
      "FPM",
      "FPL",
      "FPX"
    ]
  },
  "fixedBaseCoordinateTypeGeo": {
    "default": false,
    "platforms": [
      "EVK",
      "FacetX5",
      "Torch",
      "Postcard",
      "TX2",
      "FPM",
      "FPL",
      "FPX"
    ]
  },
  "fixedEcefX": {
    "default": -1280206.568,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "fixedEcefY": {
    "default": -4716804.403,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "fixedEcefZ": {
    "default": 4086665.484,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "fixedLat": {
    "default": 40.09029479,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "fixedLong": {
    "default": -105.18505761,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "lg290pRtkDifferentialAge": {
    "default": 120,
    "platforms": [
      "FPL",
      "Postcard",
      "TX2"
    ]
  },
  "lg290pRtkDifferentialSourceType": {
    "default": 0,
    "platforms": [
      "FPL",
      "Postcard",
      "TX2"
    ]
  },
  "lg290pRtkReliabilityLevel": {
    "default": 3,
    "platforms": [
      "FPL",
      "Postcard",
      "TX2"
    ]
  },
  "loraCoordinationFrequency": {
    "default": 910.0,
    "platforms": [
      "FPL",
      "FPM",
      "FPX",
      "Torch"
    ]
  },
  "loraSerialInteractionTimeout": {
    "default": 30,
    "platforms": [
      "Torch"
    ]
  },
  "maxLogLength": {
    "default": 1440,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "maxLogTime": {
    "default": 1440,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard"
    ]
  },
  "measurementScale": {
    "default": 0,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "minElev": {
    "default": 10,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntpPollExponent": {
    "default": 6,
    "platforms": [
      "EVK"
    ]
  },
  "ntpPrecision": {
    "default": -20,
    "platforms": [
      "EVK"
    ]
  },
  "ntpReferenceId": {
    "default": null,
    "platforms": [
      "EVK"
    ]
  },
  "ntpRootDelay": {
    "default": 0,
    "platforms": [
      "EVK"
    ]
  },
  "ntpRootDispersion": {
    "default": 1000,
    "platforms": [
      "EVK"
    ]
  },
  "ntripClientCasterHost": {
    "default": "rtk2go.com",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripClientCasterPort": {
    "default": 2101,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripClientCasterUser": {
    "default": "test@test.com",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripClientCasterUserPW": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripClientMountPoint": {
    "default": "bldr_SparkFun1",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripClientMountPointPW": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripClientTransmitGGA": {
    "default": true,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterEnabled_0": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterEnabled_1": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterEnabled_2": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterEnabled_3": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterHost_0": {
    "default": "rtk2go.com",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterHost_1": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterHost_2": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterHost_3": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterPort_0": {
    "default": 2101,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterPort_1": {
    "default": 2101,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterPort_2": {
    "default": 2101,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterPort_3": {
    "default": 2101,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUserPW_0": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUserPW_1": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUserPW_2": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUserPW_3": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUser_0": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUser_1": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUser_2": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerCasterUser_3": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPointPW_0": {
    "default": "WR5wRo4H",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPointPW_1": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPointPW_2": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPointPW_3": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPoint_0": {
    "default": "bldr_dwntwn2",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPoint_1": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPoint_2": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "ntripServerMountPoint_3": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "observationPositionAccuracy": {
    "default": 5.0,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "observationSeconds": {
    "default": 60,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "outputTipAltitude": {
    "default": false,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "pointPerfectService": {
    "default": 0,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "pppDatum": {
    "default": 1,
    "platforms": [
      "FPL",
      "FPX",
      "Postcard",
      "TX2"
    ]
  },
  "pppHorizontalConvergence": {
    "default": 0.1,
    "platforms": [
      "FPL",
      "FPX",
      "Postcard",
      "TX2"
    ]
  },
  "pppMode": {
    "default": 2,
    "platforms": [
      "FPL",
      "FPX",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "pppTimeout": {
    "default": 120,
    "platforms": [
      "FPL",
      "FPX",
      "Postcard",
      "TX2"
    ]
  },
  "pppVerticalConvergence": {
    "default": 0.15,
    "platforms": [
      "FPL",
      "FPX",
      "Postcard",
      "TX2"
    ]
  },
  "profileName": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "radioPortBaud": {
    "default": 57600,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "rebootMinutes": {
    "default": 0,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "rtcm1033AntennaDescriptor": {
    "default": "ADVNULLANTENNA",
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "rtcm1033AntennaSerialNr": {
    "default": "Unknown",
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "rtcm1033AntennaSetupID": {
    "default": 0,
    "platforms": [
      "FPL",
      "FPM",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "rtcmMinElev": {
    "default": -90,
    "platforms": [
      "Postcard",
      "TX2"
    ]
  },
  "shutdownNoChargeTimeoutMinutes": {
    "default": 0,
    "platforms": [
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "tcpClientHost": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "tcpClientPort": {
    "default": 2948,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "tcpOverWiFiStation": {
    "default": 1,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "tcpServerPort": {
    "default": 2948,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "udpOverWiFiStation": {
    "default": 1,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "udpServerPort": {
    "default": 10110,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "um980FixedBaseLLHSubtractSeparation": {
    "default": false,
    "platforms": [
      "Torch"
    ]
  },
  "useMSM7": {
    "default": false,
    "platforms": [
      "Postcard",
      "TX2"
    ]
  },
  "wifiConfigOverAP": {
    "default": 1,
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_0Password": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_0SSID": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_1Password": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_1SSID": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_2Password": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_2SSID": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_3Password": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  },
  "wifiNetwork_3SSID": {
    "default": "",
    "platforms": [
      "EVK",
      "FPL",
      "FPM",
      "FPX",
      "FacetX5",
      "Postcard",
      "TX2",
      "Torch"
    ]
  }
};

// Default corrections-source priority order (identity order - see
// allocateEffectiveDefaultSettings() in menuCommands.ino). Used by
// initializeArrays() in main.js to pre-seed the priority list so it's still
// correct even if the ESP32 omits every correctionsPriority_* entry.
const CORRECTIONS_SOURCE_DEFAULT_ORDER = ["External Radio", "ESP-NOW", "LoRa Radio", "Bluetooth", "USB Serial", "TCP (NTRIP)", "PPP HAS/B2b", "L-Band", "IP (PointPerfect/MQTT)"];
